/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    stories: Story;
    media: Media;
    issues: Issue;
    series: Series;
    tags: Tag;
    people: Person;
    places: Place;
    partners: Partner;
    authors: Author;
    redirects: Redirect;
    submissions: Submission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    stories: StoriesSelect<false> | StoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    channelSettings: ChannelSetting;
    navigation: Navigation;
    homePage: HomePage;
    aboutPage: AboutPage;
    disclosureSettings: DisclosureSetting;
    newsletterSettings: NewsletterSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    channelSettings: ChannelSettingsSelect<false> | ChannelSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    disclosureSettings: DisclosureSettingsSelect<false> | DisclosureSettingsSelect<true>;
    newsletterSettings: NewsletterSettingsSelect<false> | NewsletterSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * Short label above the headline — a series name, a place, or a section. Optional.
   */
  kicker?: string | null;
  /**
   * One or two sentences that add to the headline rather than repeating it. Used in cards, search, and share previews.
   */
  dek: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  channel: 'photography' | 'motion' | 'stories' | 'modeling' | 'x';
  storyType:
    | 'article'
    | 'photoEssay'
    | 'film'
    | 'videoEssay'
    | 'modelingStory'
    | 'collaboration'
    | 'interview'
    | 'fieldNote'
    | 'eventDispatch'
    | 'review';
  authors: (number | Author)[];
  /**
   * Set automatically on first publish. Editable afterwards.
   */
  publishedAt?: string | null;
  /**
   * When the work was made or the event happened, if that differs from publication.
   */
  eventDate?: string | null;
  dateDisplayMode?: ('published' | 'event' | 'both' | 'hidden') | null;
  leadMedia?: (number | null) | Media;
  leadVariant?: ('standard' | 'fullBleed' | 'split' | 'textOnly') | null;
  /**
   * A shorter headline for cards, when the full one does not fit a small crop.
   */
  cardHeadlineOverride?: string | null;
  /**
   * Higher values earn more visual weight on the homepage grid. 0 means normal.
   */
  featuredPriority?: number | null;
  /**
   * The story itself, composed from blocks.
   */
  contentBlocks?:
    | (
        | ProseBlock
        | PullQuoteBlock
        | ChapterDividerBlock
        | InterviewBlock
        | CalloutBlock
        | SourceNotesBlock
        | CorrectionBlock
        | TimelineBlock
        | ImageBlock
        | ImagePairBlock
        | TriptychBlock
        | ContactSheetBlock
        | BeforeAfterBlock
        | AnnotatedImageBlock
        | VideoBlock
        | VerticalVideoPairBlock
        | ChapterListBlock
        | PosterSequenceBlock
        | TranscriptExcerptBlock
        | CreditsBlock
        | PartnerDisclosureBlock
        | PartnerProfileBlock
        | ProductCreditsBlock
        | RelatedStoriesBlock
        | CallToActionBlock
      )[]
    | null;
  /**
   * Shown before the story when the subject genuinely warrants it. Not for mild discomfort.
   */
  contentWarning?: string | null;
  tableOfContentsMode?: ('auto' | 'always' | 'never') | null;
  tags?: (number | Tag)[] | null;
  people?: (number | Person)[] | null;
  places?: (number | Place)[] | null;
  partners?: (number | Partner)[] | null;
  series?: (number | null) | Series;
  issue?: (number | null) | Issue;
  /**
   * Editorial picks. Leave empty to blend shared people, places, tags, and series automatically.
   */
  relatedStories?: (number | Story)[] | null;
  /**
   * Deep link to the matching work on the portfolio.
   */
  relatedPortfolioUrl?: string | null;
  /**
   * Everyone whose work appears here. Spelling matters; check it.
   */
  credits?:
    | {
        role: string;
        name: string;
        /**
         * Link to a person record when one exists.
         */
        person?: (number | null) | Person;
        /**
         * Their site or profile.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Required when a partner relationship is paid, gifted, affiliate, or ambassador. Shown before the story, not buried at the end.
   */
  disclosure?: string | null;
  /**
   * Internal notes on how this work may be used.
   */
  usageNotes?: string | null;
  /**
   * Blocks publication before this date.
   */
  embargoUntil?: string | null;
  approvalStatus?: ('draft' | 'editorial-review' | 'rights-review' | 'ready') | null;
  /**
   * Overrides the headline in search results and shares. Leave blank to use the headline.
   */
  seoTitle?: string | null;
  /**
   * Leave blank to use the dek. Aim for 120–160 characters.
   */
  seoDescription?: string | null;
  /**
   * Overrides the share image. Leave blank to generate channel-aware art from the lead media.
   */
  ogMedia?: (number | null) | Media;
  /**
   * Only when this piece was first published elsewhere and that version is authoritative.
   */
  canonicalUrl?: string | null;
  /**
   * Excludes this from search engines, sitemaps, and feeds. It stays reachable by direct link.
   */
  noIndex?: boolean | null;
  readingMinutes?: number | null;
  watchSeconds?: number | null;
  wordCount?: number | null;
  /**
   * Flattened text used to build the Postgres search vector.
   */
  searchDocument?: string | null;
  contentHash?: string | null;
  legacySourceId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  role?: string | null;
  bio?: string | null;
  portrait?: (number | null) | Media;
  /**
   * Optional link to a CMS account, so an author can be shown their own drafts.
   */
  user?: (number | null) | User;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Originals stay private. Only approved derivatives are served publicly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  kind: 'image' | 'video' | 'audio' | 'document';
  /**
   * Internal label. Not shown to readers.
   */
  title: string;
  /**
   * What the image shows and why it is here. Written by a person — never auto-generated and published unreviewed. Leave blank only if purely decorative.
   */
  alt?: string | null;
  /**
   * Marks this as presentational, so it is hidden from screen readers instead of announced with empty alt text.
   */
  decorative?: boolean | null;
  /**
   * Visible caption. This is editorial copy, distinct from alt text — never use one as the other.
   */
  caption?: string | null;
  /**
   * Visible credit line, e.g. "Dorvell Ferguson Jr."
   */
  credit?: string | null;
  /**
   * Everyone whose work appears here. Spelling matters; check it.
   */
  credits?:
    | {
        role: string;
        name: string;
        /**
         * Link to a person record when one exists.
         */
        person?: (number | null) | Person;
        /**
         * Their site or profile.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  capturedAt?: string | null;
  place?: (number | null) | Place;
  people?: (number | Person)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Percentage from the top-left that must survive every responsive crop. Defaults to centre.
   */
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  /**
   * Tiny placeholder generated during derivative processing.
   */
  blurDataURL?: string | null;
  /**
   * Used to tint surfaces around this image.
   */
  dominantColor?: string | null;
  durationSeconds?: number | null;
  aspectRatio?: string | null;
  /**
   * Set by the Mux webhook once encoding completes.
   */
  muxPlaybackId?: string | null;
  processingStatus?: ('none' | 'processing' | 'ready' | 'failed') | null;
  poster?: (number | null) | Media;
  captions?:
    | {
        label: string;
        srcLang: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Required for anything with dialogue or meaningful sound. Also feeds search.
   */
  transcript?: string | null;
  /**
   * For dialogue-free films, describe what happens. Without it the piece is inaccessible to a reader who cannot see it.
   */
  visualDescription?: string | null;
  checksum?: string | null;
  perceptualHash?: string | null;
  /**
   * Where this came from, for provenance.
   */
  sourceUrl?: string | null;
  legacySourceId?: string | null;
  /**
   * Only "Approved" may appear on a published page.
   */
  rightsStatus: 'needs-review' | 'approved' | 'restricted' | 'blocked';
  consentStatus: 'not-required' | 'needs-review' | 'obtained' | 'refused';
  /**
   * Who owns this work. Often Dorvell, but not always — commissioned, agency, and campaign work frequently is not.
   */
  rightsOwner?: string | null;
  /**
   * Contract, invoice, release, or licence reference.
   */
  licenseReference?: string | null;
  /**
   * Where this may appear and for how long. Record agency or campaign restrictions here.
   */
  usageScope?: string | null;
  /**
   * Leave blank for perpetual rights.
   */
  usageExpiresAt?: string | null;
  /**
   * Do not publish before this date.
   */
  embargoUntil?: string | null;
  /**
   * Flags material needing elevated review — minors, private events, medical or distressing content.
   */
  sensitive?: boolean | null;
  /**
   * Stamped automatically when the rights status is approved.
   */
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  /**
   * Internal. Never rendered publicly.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  kind?: ('subject' | 'collaborator' | 'interviewee' | 'cast' | 'crew' | 'client')[] | null;
  /**
   * Off by default. Only enable when this person is a genuine editorial subject and is comfortable being one.
   */
  hasPublicPage?: boolean | null;
  /**
   * What they do. One line.
   */
  role?: string | null;
  bio?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Set by the migration importer. Makes re-imports idempotent.
   */
  legacySourceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  kind?: ('venue' | 'city' | 'region' | 'studio' | 'outdoor') | null;
  locality?: string | null;
  region?: string | null;
  country?: string | null;
  description?: string | null;
  /**
   * Private residences and restricted locations. Suppresses any public place page and hides precise location data.
   */
  isPrivate?: boolean | null;
  legacySourceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  label: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  /**
   * Keeps "Photojournalism" (subject) distinct from "Photo Essay" (format) and "cinematic" (mood).
   */
  kind: 'subject' | 'format' | 'technique' | 'mood';
  status: 'active' | 'merged' | 'deprecated';
  /**
   * Requests for this tag redirect here.
   */
  mergedInto?: (number | null) | Tag;
  /**
   * Optional hierarchy, e.g. Runway under Fashion.
   */
  parent?: (number | null) | Tag;
  /**
   * Alternate spellings that should find this tag in search. Not shown to readers.
   */
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Where this tag is normally offered. Not a restriction.
   */
  channelAffinity?: ('photography' | 'motion' | 'stories' | 'modeling' | 'x')[] | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'author' | 'mediaManager' | 'partnerReviewer')[];
  /**
   * Internal job title. Bylines live in the authors collection.
   */
  title?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock".
 */
export interface ProseBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Reading measure keeps lines at 60–75 characters. Widen only for tables or lists that need it.
   */
  width?: ('measure' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  attribution?: string | null;
  person?: (number | null) | Person;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChapterDividerBlock".
 */
export interface ChapterDividerBlock {
  /**
   * Optional chapter name.
   */
  label?: string | null;
  /**
   * Optional id for the table of contents to link to.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'chapterDivider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InterviewBlock".
 */
export interface InterviewBlock {
  exchanges: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * Used for the speaker label and for structured data.
   */
  intervieweeName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'interview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  tone?: ('note' | 'technique' | 'context') | null;
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SourceNotesBlock".
 */
export interface SourceNotesBlock {
  notes: {
    text: string;
    url?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'sourceNotes';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorrectionBlock".
 */
export interface CorrectionBlock {
  kind: 'update' | 'correction';
  date: string;
  note: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'correction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  entries: {
    label: string;
    when: string;
    detail?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  media: number | Media;
  /**
   * Full bleed should mark a shift in the story — a chapter, a climax, a change of format. Not every strong frame.
   */
  presentation?: ('contained' | 'wide' | 'fullBleed') | null;
  /**
   * Overrides the caption on the media record.
   */
  caption?: string | null;
  /**
   * Only when this usage needs a different credit line.
   */
  creditOverride?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImagePairBlock".
 */
export interface ImagePairBlock {
  left: number | Media;
  right: number | Media;
  alignment?: ('top' | 'baseline' | 'match') | null;
  /**
   * Overrides the caption on the media record.
   */
  caption?: string | null;
  /**
   * Only when this usage needs a different credit line.
   */
  creditOverride?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imagePair';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TriptychBlock".
 */
export interface TriptychBlock {
  images: {
    media: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'triptych';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSheetBlock".
 */
export interface ContactSheetBlock {
  title?: string | null;
  frames: {
    media: number | Media;
    caption?: string | null;
    /**
     * Marks the frame that was chosen, as a grease-pencil ring.
     */
    selected?: boolean | null;
    id?: string | null;
  }[];
  showFrameNumbers?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactSheet';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeforeAfterBlock".
 */
export interface BeforeAfterBlock {
  before: number | Media;
  after: number | Media;
  beforeLabel?: string | null;
  afterLabel?: string | null;
  /**
   * What changed and why — the point of showing both.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'beforeAfter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnotatedImageBlock".
 */
export interface AnnotatedImageBlock {
  media: number | Media;
  /**
   * Positions are percentages. Annotations are also listed below the image, so the information is never hover-only.
   */
  annotations: {
    x: number;
    y: number;
    label: string;
    detail?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'annotatedImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  media: number | Media;
  presentation?: ('contained' | 'wide' | 'fullBleed') | null;
  caption?: string | null;
  /**
   * Only for short silent loops. Muted, paused offscreen, omitted in reduced-data mode, and always given a pause control.
   */
  autoplayLoop?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerticalVideoPairBlock".
 */
export interface VerticalVideoPairBlock {
  left: number | Media;
  right?: (number | null) | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'verticalVideoPair';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChapterListBlock".
 */
export interface ChapterListBlock {
  /**
   * Authored by hand, not auto-detected. These become both seek targets and Clip structured data, so they must be accurate.
   */
  chapters: {
    startSeconds: number;
    title: string;
    note?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'chapterList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PosterSequenceBlock".
 */
export interface PosterSequenceBlock {
  posters: {
    media: number | Media;
    label?: string | null;
    story?: (number | null) | Story;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'posterSequence';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TranscriptExcerptBlock".
 */
export interface TranscriptExcerptBlock {
  source?: (number | null) | Media;
  excerpt: string;
  startSeconds?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'transcriptExcerpt';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreditsBlock".
 */
export interface CreditsBlock {
  title?: string | null;
  /**
   * Everyone whose work appears here. Spelling matters; check it.
   */
  credits?:
    | {
        role: string;
        name: string;
        /**
         * Link to a person record when one exists.
         */
        person?: (number | null) | Person;
        /**
         * Their site or profile.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'creditsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerDisclosureBlock".
 */
export interface PartnerDisclosureBlock {
  partner: number | Partner;
  /**
   * Leave blank to use the standard wording for this relationship type from disclosure settings.
   */
  statement?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerDisclosure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  /**
   * State what the relationship actually was. Defaults to the weakest claim on purpose.
   */
  relationshipType:
    | 'sponsor'
    | 'paid-partnership'
    | 'client'
    | 'ambassador'
    | 'gifted'
    | 'affiliate'
    | 'collaborator'
    | 'event-host'
    | 'editorial-mention';
  /**
   * A case file cannot publish until this is verified. PacSun and Cold Culture are unverified until confirmed.
   */
  verificationStatus: 'unverified' | 'verified' | 'disputed';
  kind?: ('brand' | 'publication' | 'institution' | 'team' | 'agency' | 'venue') | null;
  website?: string | null;
  summary?: string | null;
  logo?: (number | null) | Media;
  /**
   * Optional approved brand accent as a hex value. It is contrast-clamped before use and can only tint the accent role — never body text or the focus indicator.
   */
  accentColor?: string | null;
  legacySourceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerProfileBlock".
 */
export interface PartnerProfileBlock {
  partner: number | Partner;
  /**
   * Exactly what Dorvell did.
   */
  role?: string | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerProfile';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductCreditsBlock".
 */
export interface ProductCreditsBlock {
  items: {
    item: string;
    brand?: string | null;
    partner?: (number | null) | Partner;
    url?: string | null;
    /**
     * Adds rel="sponsored" and surfaces the affiliate disclosure.
     */
    isAffiliate?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'productCredits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedStoriesBlock".
 */
export interface RelatedStoriesBlock {
  title?: string | null;
  /**
   * Leave empty to blend editorial selection with shared people, places, tags, and series.
   */
  stories?: (number | Story)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedStories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  kind: 'newsletter' | 'portfolio' | 'inquiry';
  heading?: string | null;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  title: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  dek?: string | null;
  /**
   * Leave blank for a series that spans channels.
   */
  channel?: ('photography' | 'motion' | 'stories' | 'modeling' | 'x') | null;
  status?: ('ongoing' | 'complete' | 'on-hold') | null;
  coverMedia?: (number | null) | Media;
  legacySourceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  /**
   * Rendered as ISSUE 001.
   */
  number: number;
  title: string;
  /**
   * Permanent part of the public URL. Changing this on a published item breaks existing links — add a redirect if you do.
   */
  slug: string;
  /**
   * What this issue is about, in two or three sentences.
   */
  statement?: string | null;
  /**
   * Only one issue should be Current. It drives the homepage issue line.
   */
  editionStatus?: ('in-production' | 'current' | 'archived') | null;
  publishedAt?: string | null;
  coverMedia?: (number | null) | Media;
  /**
   * The dominant feature on the homepage while this issue is current.
   */
  leadStory?: (number | null) | Story;
  /**
   * Ordered sequence for the issue rail. Order here is the order readers see — it is an editorial decision, not recency.
   */
  railStories?: (number | Story)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path only, starting with a slash. For example /story/old-slug
   */
  from: string;
  /**
   * A path on this site, or a full URL for an external destination.
   */
  to: string;
  statusCode: '301' | '302';
  reason?: ('slug-change' | 'legacy' | 'tag-merge' | 'removed') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Retention: reviewed submissions are purged after 12 months.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  kind: 'general' | 'commission' | 'casting' | 'press' | 'correction';
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  /**
   * Which page this was sent from.
   */
  sourcePath?: string | null;
  status?: ('new' | 'replied' | 'archived' | 'spam') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'issues';
        value: number | Issue;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  kicker?: T;
  dek?: T;
  slug?: T;
  channel?: T;
  storyType?: T;
  authors?: T;
  publishedAt?: T;
  eventDate?: T;
  dateDisplayMode?: T;
  leadMedia?: T;
  leadVariant?: T;
  cardHeadlineOverride?: T;
  featuredPriority?: T;
  contentBlocks?:
    | T
    | {
        prose?: T | ProseBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        chapterDivider?: T | ChapterDividerBlockSelect<T>;
        interview?: T | InterviewBlockSelect<T>;
        callout?: T | CalloutBlockSelect<T>;
        sourceNotes?: T | SourceNotesBlockSelect<T>;
        correction?: T | CorrectionBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        imagePair?: T | ImagePairBlockSelect<T>;
        triptych?: T | TriptychBlockSelect<T>;
        contactSheet?: T | ContactSheetBlockSelect<T>;
        beforeAfter?: T | BeforeAfterBlockSelect<T>;
        annotatedImage?: T | AnnotatedImageBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        verticalVideoPair?: T | VerticalVideoPairBlockSelect<T>;
        chapterList?: T | ChapterListBlockSelect<T>;
        posterSequence?: T | PosterSequenceBlockSelect<T>;
        transcriptExcerpt?: T | TranscriptExcerptBlockSelect<T>;
        creditsBlock?: T | CreditsBlockSelect<T>;
        partnerDisclosure?: T | PartnerDisclosureBlockSelect<T>;
        partnerProfile?: T | PartnerProfileBlockSelect<T>;
        productCredits?: T | ProductCreditsBlockSelect<T>;
        relatedStories?: T | RelatedStoriesBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
      };
  contentWarning?: T;
  tableOfContentsMode?: T;
  tags?: T;
  people?: T;
  places?: T;
  partners?: T;
  series?: T;
  issue?: T;
  relatedStories?: T;
  relatedPortfolioUrl?: T;
  credits?:
    | T
    | {
        role?: T;
        name?: T;
        person?: T;
        url?: T;
        id?: T;
      };
  disclosure?: T;
  usageNotes?: T;
  embargoUntil?: T;
  approvalStatus?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogMedia?: T;
  canonicalUrl?: T;
  noIndex?: T;
  readingMinutes?: T;
  watchSeconds?: T;
  wordCount?: T;
  searchDocument?: T;
  contentHash?: T;
  legacySourceId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock_select".
 */
export interface ProseBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock_select".
 */
export interface PullQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  person?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChapterDividerBlock_select".
 */
export interface ChapterDividerBlockSelect<T extends boolean = true> {
  label?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InterviewBlock_select".
 */
export interface InterviewBlockSelect<T extends boolean = true> {
  exchanges?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  intervieweeName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock_select".
 */
export interface CalloutBlockSelect<T extends boolean = true> {
  tone?: T;
  title?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SourceNotesBlock_select".
 */
export interface SourceNotesBlockSelect<T extends boolean = true> {
  notes?:
    | T
    | {
        text?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorrectionBlock_select".
 */
export interface CorrectionBlockSelect<T extends boolean = true> {
  kind?: T;
  date?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  entries?:
    | T
    | {
        label?: T;
        when?: T;
        detail?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  media?: T;
  presentation?: T;
  caption?: T;
  creditOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImagePairBlock_select".
 */
export interface ImagePairBlockSelect<T extends boolean = true> {
  left?: T;
  right?: T;
  alignment?: T;
  caption?: T;
  creditOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TriptychBlock_select".
 */
export interface TriptychBlockSelect<T extends boolean = true> {
  images?:
    | T
    | {
        media?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSheetBlock_select".
 */
export interface ContactSheetBlockSelect<T extends boolean = true> {
  title?: T;
  frames?:
    | T
    | {
        media?: T;
        caption?: T;
        selected?: T;
        id?: T;
      };
  showFrameNumbers?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BeforeAfterBlock_select".
 */
export interface BeforeAfterBlockSelect<T extends boolean = true> {
  before?: T;
  after?: T;
  beforeLabel?: T;
  afterLabel?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnotatedImageBlock_select".
 */
export interface AnnotatedImageBlockSelect<T extends boolean = true> {
  media?: T;
  annotations?:
    | T
    | {
        x?: T;
        y?: T;
        label?: T;
        detail?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  media?: T;
  presentation?: T;
  caption?: T;
  autoplayLoop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerticalVideoPairBlock_select".
 */
export interface VerticalVideoPairBlockSelect<T extends boolean = true> {
  left?: T;
  right?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChapterListBlock_select".
 */
export interface ChapterListBlockSelect<T extends boolean = true> {
  chapters?:
    | T
    | {
        startSeconds?: T;
        title?: T;
        note?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PosterSequenceBlock_select".
 */
export interface PosterSequenceBlockSelect<T extends boolean = true> {
  posters?:
    | T
    | {
        media?: T;
        label?: T;
        story?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TranscriptExcerptBlock_select".
 */
export interface TranscriptExcerptBlockSelect<T extends boolean = true> {
  source?: T;
  excerpt?: T;
  startSeconds?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CreditsBlock_select".
 */
export interface CreditsBlockSelect<T extends boolean = true> {
  title?: T;
  credits?:
    | T
    | {
        role?: T;
        name?: T;
        person?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerDisclosureBlock_select".
 */
export interface PartnerDisclosureBlockSelect<T extends boolean = true> {
  partner?: T;
  statement?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerProfileBlock_select".
 */
export interface PartnerProfileBlockSelect<T extends boolean = true> {
  partner?: T;
  role?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductCreditsBlock_select".
 */
export interface ProductCreditsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        item?: T;
        brand?: T;
        partner?: T;
        url?: T;
        isAffiliate?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedStoriesBlock_select".
 */
export interface RelatedStoriesBlockSelect<T extends boolean = true> {
  title?: T;
  stories?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  kind?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  credits?:
    | T
    | {
        role?: T;
        name?: T;
        person?: T;
        url?: T;
        id?: T;
      };
  capturedAt?: T;
  place?: T;
  people?: T;
  tags?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  blurDataURL?: T;
  dominantColor?: T;
  durationSeconds?: T;
  aspectRatio?: T;
  muxPlaybackId?: T;
  processingStatus?: T;
  poster?: T;
  captions?:
    | T
    | {
        label?: T;
        srcLang?: T;
        file?: T;
        id?: T;
      };
  transcript?: T;
  visualDescription?: T;
  checksum?: T;
  perceptualHash?: T;
  sourceUrl?: T;
  legacySourceId?: T;
  rightsStatus?: T;
  consentStatus?: T;
  rightsOwner?: T;
  licenseReference?: T;
  usageScope?: T;
  usageExpiresAt?: T;
  embargoUntil?: T;
  sensitive?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  slug?: T;
  statement?: T;
  editionStatus?: T;
  publishedAt?: T;
  coverMedia?: T;
  leadStory?: T;
  railStories?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  dek?: T;
  channel?: T;
  status?: T;
  coverMedia?: T;
  legacySourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  kind?: T;
  status?: T;
  mergedInto?: T;
  parent?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  channelAffinity?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  hasPublicPage?: T;
  role?: T;
  bio?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legacySourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  locality?: T;
  region?: T;
  country?: T;
  description?: T;
  isPrivate?: T;
  legacySourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  relationshipType?: T;
  verificationStatus?: T;
  kind?: T;
  website?: T;
  summary?: T;
  logo?: T;
  accentColor?: T;
  legacySourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  portrait?: T;
  user?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  reason?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  kind?: T;
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  sourcePath?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline: string;
  /**
   * One paragraph explaining the publication. Used in the footer and share defaults.
   */
  statement?: string | null;
  /**
   * Fallback for pages with no description of their own.
   */
  defaultSeoDescription?: string | null;
  defaultShareImage?: (number | null) | Media;
  contactEmail?: string | null;
  /**
   * The bridge to the portfolio. Never embedded or restyled.
   */
  portfolioUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Visible channel names. The /stories and /modeling labels are still provisional — editing them here is safe and requires no development work.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channelSettings".
 */
export interface ChannelSetting {
  id: number;
  channels?:
    | {
        /**
         * Which channel this row configures. The route is fixed.
         */
        key: 'photography' | 'motion' | 'stories' | 'modeling' | 'x';
        /**
         * The public name readers see.
         */
        label?: string | null;
        tagline?: string | null;
        description?: string | null;
        /**
         * Leads the channel landing page.
         */
        featuredStory?: (number | null) | Story;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerCtaLabel?: string | null;
  headerCtaHref?: string | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        group?: ('read' | 'legal') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  /**
   * Drives the issue line and the issue rail.
   */
  currentIssue?: (number | null) | Issue;
  /**
   * Overrides the current issue’s lead story.
   */
  leadStory?: (number | null) | Story;
  /**
   * Order here is the order on the page.
   */
  sections?:
    | {
        kind: 'channelStrip' | 'issueRail' | 'latestGrid' | 'fromArchive' | 'fieldNote' | 'newsletter' | 'credits';
        heading?: string | null;
        /**
         * Leave empty to fill automatically.
         */
        stories?: (number | Story)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  headline?: string | null;
  lead?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  portrait?: (number | null) | Media;
  milestones?:
    | {
        title: string;
        organisation?: string | null;
        era?: string | null;
        detail?: string | null;
        /**
         * Unverified entries are marked as pending rather than stated as fact. Confirm before any press use.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclosureSettings".
 */
export interface DisclosureSetting {
  id: number;
  statements?:
    | {
        relationshipType:
          | 'sponsor'
          | 'paid-partnership'
          | 'client'
          | 'ambassador'
          | 'gifted'
          | 'affiliate'
          | 'collaborator'
          | 'event-host'
          | 'editorial-mention';
        statement: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The full disclosure policy shown at /disclosures.
   */
  policyBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterSettings".
 */
export interface NewsletterSetting {
  id: number;
  name?: string | null;
  /**
   * What a subscriber actually receives. Be specific and honest.
   */
  promise?: string | null;
  /**
   * Stated up front. Do not promise a cadence you cannot keep.
   */
  frequency?: string | null;
  privacyNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  statement?: T;
  defaultSeoDescription?: T;
  defaultShareImage?: T;
  contactEmail?: T;
  portfolioUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channelSettings_select".
 */
export interface ChannelSettingsSelect<T extends boolean = true> {
  channels?:
    | T
    | {
        key?: T;
        label?: T;
        tagline?: T;
        description?: T;
        featuredStory?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerCtaLabel?: T;
  headerCtaHref?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        group?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  currentIssue?: T;
  leadStory?: T;
  sections?:
    | T
    | {
        kind?: T;
        heading?: T;
        stories?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  headline?: T;
  lead?: T;
  body?: T;
  portrait?: T;
  milestones?:
    | T
    | {
        title?: T;
        organisation?: T;
        era?: T;
        detail?: T;
        verified?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclosureSettings_select".
 */
export interface DisclosureSettingsSelect<T extends boolean = true> {
  statements?:
    | T
    | {
        relationshipType?: T;
        statement?: T;
        id?: T;
      };
  policyBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletterSettings_select".
 */
export interface NewsletterSettingsSelect<T extends boolean = true> {
  name?: T;
  promise?: T;
  frequency?: T;
  privacyNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'stories';
      value: number | Story;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}